package Clases;

import Conexiones.Conexion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Usuario
 */
public class MenuNormal extends javax.swing.JFrame {
    
    /**
     * Creates new form MenuNormal
     */
    public MenuNormal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CierreSesion = new javax.swing.JButton();
        aBuscar = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        categoria = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CierreSesion.setText("Cerrar sesión");
        CierreSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CierreSesionActionPerformed(evt);
            }
        });

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Canción", "Album", "Artista" }));
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoria, 0, 234, Short.MAX_VALUE)
                            .addComponent(aBuscar))
                        .addGap(18, 18, 18)
                        .addComponent(Buscar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CierreSesion)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(CierreSesion)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        
        //category=categoria.getSelectedItem().toString();
    }//GEN-LAST:event_categoriaActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        String buscando = aBuscar.getText();
        String nombre = null;
        String category = null;
        Connection conn =null;
        Statement pst=null;
        ResultSet rs=null;
        category=categoria.getSelectedItem().toString();
        
     try{
           Conexion conect1 = new Conexion();
           conn = conect1.getConnection();
           pst = conn.createStatement();
           String sql = null;
           sql  = "select * from informacion ";
           rs=pst.executeQuery(sql);
            
            
           
          
           InfoNormal ob = new InfoNormal();
           while(rs.next()){
               if(category.equals("Canción")){
                   
                   nombre = rs.getString("nombreC");
                }
            if(category.equals("Album")){
                   
                   nombre = rs.getString("Album");
                }
            if(category.equals("Artista")){
                   
                   nombre = rs.getString("Artista");
                }
               
               if(nombre.equals(buscando)){
                   
                   
                   if(category.equals("Canción")){
                       ob.cancion.setText(buscando);
                       ob.artista.setText(rs.getString("Artista"));
                       ob.album.setText(rs.getString("Album"));
                   }
                   if(category.equals("Album")){
                       ob.album.setText(buscando);
                       ob.artista.setText(rs.getString("Artista"));
                       ob.cancion.setText(rs.getString("nombreC"));
                   }
                   if(category.equals("Artista")){
                       ob.artista.setText(buscando);
                       ob.album.setText(rs.getString("Album"));
                       ob.cancion.setText(rs.getString("nombreC"));
                   }
                   JOptionPane.showMessageDialog(null,category+" Encontrad@");
                   ob.setVisible(true);
                   this.setVisible(false);
                   break;
               }
           }
     }
                catch(SQLException e){
            JOptionPane.showMessageDialog(null,"no da");
        }
               
        
    
        
        
    }//GEN-LAST:event_BuscarActionPerformed

    private void CierreSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CierreSesionActionPerformed
        Interfaz x = new Interfaz();
        x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CierreSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNormal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuNormal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton CierreSesion;
    private javax.swing.JTextField aBuscar;
    private javax.swing.JComboBox<String> categoria;
    // End of variables declaration//GEN-END:variables
}
